version: '3.2'

services:
  elasticsearch:
    build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    restart: always
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: single-node
        ELASTIC_PASSWORD: $ELASTIC_PASSWORD
        xpack.security.enabled: $ELASTIC_SECURITY

  kibana:
    build:
        context: kibana/
        args:
          ELK_VERSION: $ELK_VERSION
    container_name: kibana
    restart: always
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
        - "5601:5601"
    environment:
        ELASTICSEARCH_USERNAME: elastic
        ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
        - elasticsearch

  ngnix:
    build: nginx/
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - elasticsearch
      - kibana

volumes:
    elasticsearch: